/**
 * Create DSP Page Component
 * 
 * This page provides a comprehensive form interface for creating new DSP (Demand-Side Platform) partners.
 * It allows users to configure all necessary DSP settings including basic information, status, connector settings,
 * inventory access controls, and advanced configurations.
 * 
 * Features:
 * - Complete DSP creation form with validation
 * - Basic information configuration (name, status, connector kind)
 * - Revenue settings (auction type, default floor price)
 * - General settings (auditing, multi-ad kind support)
 * - Inventory access controls (broker, prebid client, prebid server)
 * - Image configuration settings (quality, cropper)
 * - Form validation and error handling
 * - Loading states during DSP creation
 * - Success feedback and automatic navigation
 * - Integration with authentication system
 * - Responsive design for mobile and desktop
 * - API integration with proper payload structure
 */

import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import {
  ArrowLeft,
  Plus,
  AlertCircle,
  Loader2,
  CheckCircle
} from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { API_ENDPOINTS } from "@/config/api";

export default function CreateDSP() {
  const navigate = useNavigate();
  const { getToken } = useAuth();
  
  // Form state
  const [formData, setFormData] = useState({
    name: "",
    status: "PRODUCTION",
    connector_kind: "",
    comments: "",
    inventory_access_broker: false,
    inventory_access_prebid: false,
    inventory_access_prebid_server: false,
    revenue_auction_type: "FIRST_PRICE",
    revenue_default_floor_price: 0,
    auditing: "ALLOW_ALL",
    allow_multi_adkind: false,
    image_config_preview_image_quality: "NORMAL",
    image_config_cropper: "THUMBOR",
    connector_win_notice_kind: "SERVER"
  });
  
  const [authToken, setAuthToken] = useState("");
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  // Load saved token on component mount
  useEffect(() => {
    const savedToken = getToken();
    if (savedToken) {
      setAuthToken(savedToken);
    }
  }, [getToken]);

  // Helper function to get the token to use (form token or saved token)
  const getTokenToUse = () => {
    return authToken.trim() || getToken();
  };

  // Handle form input changes
  const handleInputChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Handle switch changes
  const handleSwitchChange = (field, checked) => {
    setFormData(prev => ({
      ...prev,
      [field]: checked
    }));
  };

  // Submit form to create DSP
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const token = getTokenToUse();
      if (!token) {
        throw new Error("Please login first");
      }

      // Prepare payload according to the API specification
      const payload = {
        "Data": {
          "name": formData.name,
          "status": formData.status,
          "uid": "", // Will be generated by the API
          "seat_id": "", // Empty for new DSP
          "cookie_sync": [],
          "inventory_access_broker": formData.inventory_access_broker,
          "inventory_access_prebid": formData.inventory_access_prebid,
          "inventory_access_prebid_server": formData.inventory_access_prebid_server,
          "updated_at": "", // Will be set by the API
          "connector_privacy_vendor_id": null,
          "image_config_preview_image_quality": formData.image_config_preview_image_quality,
          "image_config_cropper": formData.image_config_cropper,
          "connector_kind": formData.connector_kind,
          "connector_win_notice_kind": formData.connector_win_notice_kind,
          "revenue_auction_type": formData.revenue_auction_type,
          "revenue_default_floor_price": formData.revenue_default_floor_price,
          "auditing": formData.auditing,
          "allow_multi_adkind": formData.allow_multi_adkind,
          "comments": formData.comments,
          "partner_endpoint": [],
          "partner_targeting": [],
          "connector_contents": {}
        },
        "Kind": "partner"
      };

      const response = await fetch(API_ENDPOINTS.PARTNERS, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-ayl-auth-token": token
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
      }

      const result = await response.json();
      setSuccess(true);
      
      // Redirect to DSP Dashboard after successful creation
      setTimeout(() => {
        navigate('/DSPDashboard');
      }, 2000);

    } catch (err) {
      setError(`Error creating DSP: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      <div className="max-w-4xl mx-auto p-6 lg:p-8">
        {/* Back Button */}
        <div className="mb-6">
          <Button
            variant="outline"
            onClick={() => navigate('/DSPDashboard')}
            className="flex items-center gap-2 hover:bg-blue-50 hover:border-blue-300 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to DSP Dashboard
          </Button>
        </div>

        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-900 mb-2">Create New DSP</h1>
          <p className="text-slate-600">Add a new Demand-Side Platform to your network</p>
        </div>

        {/* Success Message */}
        {success && (
          <Alert className="mb-6 border-green-200 bg-green-50">
            <CheckCircle className="h-4 w-4 text-green-600" />
            <AlertDescription className="text-green-800">
              DSP created successfully! Redirecting to DSP Dashboard...
            </AlertDescription>
          </Alert>
        )}

        {/* Error Message */}
        {error && (
          <Alert variant="destructive" className="mb-6">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Main Form */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Plus className="w-5 h-5" />
              DSP Configuration
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Basic Information */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="name">DSP Name *</Label>
                  <Input
                    id="name"
                    type="text"
                    placeholder="Enter DSP name"
                    value={formData.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    required
                    disabled={loading}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="status">Status *</Label>
                  <Select
                    value={formData.status}
                    onValueChange={(value) => handleInputChange('status', value)}
                    disabled={loading}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="PRODUCTION">PRODUCTION</SelectItem>
                      <SelectItem value="DISABLED">DISABLED</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="connector_kind">Connector Kind</Label>
                  <Input
                    id="connector_kind"
                    type="text"
                    placeholder="e.g., OPEN_RTB_2_5"
                    value={formData.connector_kind}
                    onChange={(e) => handleInputChange('connector_kind', e.target.value)}
                    disabled={loading}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="revenue_auction_type">Revenue Auction Type</Label>
                  <Select
                    value={formData.revenue_auction_type}
                    onValueChange={(value) => handleInputChange('revenue_auction_type', value)}
                    disabled={loading}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select auction type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="FIRST_PRICE">First Price</SelectItem>
                      <SelectItem value="SECOND_PRICE">Second Price</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="revenue_default_floor_price">Default Floor Price</Label>
                  <Input
                    id="revenue_default_floor_price"
                    type="number"
                    min="0"
                    step="0.01"
                    placeholder="0.00"
                    value={formData.revenue_default_floor_price}
                    onChange={(e) => handleInputChange('revenue_default_floor_price', parseFloat(e.target.value) || 0)}
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Comments */}
              <div className="space-y-2">
                <Label htmlFor="comments">Comments</Label>
                <Textarea
                  id="comments"
                  placeholder="Additional notes about this DSP..."
                  value={formData.comments}
                  onChange={(e) => handleInputChange('comments', e.target.value)}
                  disabled={loading}
                  rows={3}
                />
              </div>

              {/* General Settings */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900">General Settings</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="auditing">Auditing</Label>
                    <Select
                      value={formData.auditing}
                      onValueChange={(value) => handleInputChange('auditing', value)}
                      disabled={loading}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select auditing level" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="ALLOW_ALL">Allow All</SelectItem>
                        <SelectItem value="RESTRICTED">Restricted</SelectItem>
                        <SelectItem value="DISABLED">Disabled</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Switch
                      id="allow_multi_adkind"
                      checked={formData.allow_multi_adkind}
                      onCheckedChange={(checked) => handleSwitchChange('allow_multi_adkind', checked)}
                      disabled={loading}
                    />
                    <Label htmlFor="allow_multi_adkind">Allow Multi Ad Kind</Label>
                  </div>
                </div>
              </div>

              {/* Inventory Access Settings */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900">Inventory Access</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="flex items-center space-x-3">
                    <Switch
                      id="inventory_access_broker"
                      checked={formData.inventory_access_broker}
                      onCheckedChange={(checked) => handleSwitchChange('inventory_access_broker', checked)}
                      disabled={loading}
                    />
                    <Label htmlFor="inventory_access_broker">Broker Access</Label>
                  </div>

                  <div className="flex items-center space-x-3">
                    <Switch
                      id="inventory_access_prebid"
                      checked={formData.inventory_access_prebid}
                      onCheckedChange={(checked) => handleSwitchChange('inventory_access_prebid', checked)}
                      disabled={loading}
                    />
                    <Label htmlFor="inventory_access_prebid">Prebid Client</Label>
                  </div>

                  <div className="flex items-center space-x-3">
                    <Switch
                      id="inventory_access_prebid_server"
                      checked={formData.inventory_access_prebid_server}
                      onCheckedChange={(checked) => handleSwitchChange('inventory_access_prebid_server', checked)}
                      disabled={loading}
                    />
                    <Label htmlFor="inventory_access_prebid_server">Prebid Server</Label>
                  </div>
                </div>
              </div>

              {/* Image Configuration */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-slate-900">Image Configuration</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="image_config_preview_image_quality">Preview Image Quality</Label>
                    <Select
                      value={formData.image_config_preview_image_quality}
                      onValueChange={(value) => handleInputChange('image_config_preview_image_quality', value)}
                      disabled={loading}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select quality" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="LOW">Low</SelectItem>
                        <SelectItem value="NORMAL">Normal</SelectItem>
                        <SelectItem value="HIGH">High</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="image_config_cropper">Image Cropper</Label>
                    <Select
                      value={formData.image_config_cropper}
                      onValueChange={(value) => handleInputChange('image_config_cropper', value)}
                      disabled={loading}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select cropper" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="THUMBOR">Thumbor</SelectItem>
                        <SelectItem value="OTHER">Other</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>

              {/* Submit Button */}
              <div className="flex justify-end pt-6">
                <Button
                  type="submit"
                  disabled={loading || !formData.name.trim()}
                  className="flex items-center gap-2"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Creating DSP...
                    </>
                  ) : (
                    <>
                      <Plus className="w-4 h-4" />
                      Create DSP
                    </>
                  )}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
